import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import styles from "@/styles/Home.module.css";

const graphcms = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clf4fo6ho4xew01umcz8reajm/master"
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}
